In [1]:
# HW2
# 1. Anaconda is installed and been able to open / create Jupyter notebooks

# 2. Gram-Schmidt Algorithm
import numpy as np
import pandas as pd

def modified_gram_schmidt(V):
    n, m = V.shape
    Q = np.zeros((n, m))

    for i in range(n):
        # Start with the current vector
        q = V[i, :]

        # Subtract projections onto previous basis vectors
        for j in range(i):
            q -= np.dot(Q[j, :], V[i, :]) * Q[j, :]

        # Normalize the vector
        q = q / np.linalg.norm(q)

        # Store in the orthonormal basis matrix
        Q[i, :] = q

    return Q

# We are given the following matrix
V = np.array(
    [[1, 2, 2],
     [-1, 0, 2],
     [0, 0, 1]], dtype=float)

# Orthogonalize vectors
Q = modified_gram_schmidt(V)

# Display the results
df = pd.DataFrame(Q, columns=["c1", "c2", "c3"])
print(f"Here are the orthogonalized vectors: \n{df}")

Here are the orthogonalized vectors: 
         c1        c2        c3
0  0.333333  0.666667  0.666667
1 -0.666667 -0.333333  0.666667
2  0.666667 -0.666667  0.333333


In [6]:
# 3. Singular Value Decomposition (SVD)

# Implementing Singular Value Decomposition (SVD) manually using NumPy (without numpy.linalg.svd)

def svd_manual(A):
    # Compute A^T A and A A^T
    AtA = np.dot(A.T, A)  # using dot for matrix multipliation (n x n)
    AAt = np.dot(A, A.T)  # using dot for matrix multipliation (m x m)

    # Compute eigenvalues and eigenvectors
    eigvals_AtA, V = np.linalg.eigh(AtA)  # Right singular vectors
    eigvals_AAt, U = np.linalg.eigh(AAt)  # Left singular vectors

    # Sort eigenvalues and eigenvectors in descending order
    sorted_indices_AtA = np.argsort(eigvals_AtA)[::-1]
    sorted_indices_AAt = np.argsort(eigvals_AAt)[::-1]

    V = V[:, sorted_indices_AtA]
    U = U[:, sorted_indices_AAt]

    # Singular values (positive eigenvalues)
    singular_values = np.sqrt(np.maximum(eigvals_AtA[sorted_indices_AtA], 0))

    # Construct the S matrix (m x n) with singular values on the diagonal
    S = np.zeros_like(A, dtype=float)
    np.fill_diagonal(S, singular_values)

    return U, S, V.T  #Transpose V back

# Given matrix M
M = np.array([
    [1, 0, 0, 0, 2],
    [0, 0, 3, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 2, 0, 0, 0]
], dtype=float)

# Perform manual SVD
U, S, Vt = svd_manual(M)

# Function to display matrices
def display_matrix(matrix, name="Matrix"):
    print(f"\n{name}:")
    print(np.array_str(matrix, precision=4, suppress_small=True))

# Display the matrices
display_matrix(U, "U Matrix (Left Singular Vectors)")
display_matrix(S, "S Matrix (Singular Values)")
display_matrix(Vt, "Vt Matrix (Right Singular Vectors Transposed)")


U Matrix (Left Singular Vectors):
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

S Matrix (Singular Values):
[[3.     0.     0.     0.     0.    ]
 [0.     2.2361 0.     0.     0.    ]
 [0.     0.     2.     0.     0.    ]
 [0.     0.     0.     0.     0.    ]]

Vt Matrix (Right Singular Vectors Transposed):
[[ 0.      0.      1.      0.      0.    ]
 [-0.4472  0.      0.      0.     -0.8944]
 [ 0.     -1.      0.      0.      0.    ]
 [ 0.      0.      0.      1.      0.    ]
 [-0.8944  0.      0.      0.      0.4472]]


In [8]:
# 4.L^2 norm of an Nth length vector

def l2_norm(vector):
    return np.sqrt(np.sum(vector**2))

# Given vector:
vector = np.array([
    np.cos(np.pi / 4) * np.sin(np.pi / 8),
    np.sin(np.pi / 4) * np.sin(np.pi / 8),
    np.sin(np.pi / 4) * np.sin(np.pi / 8),
    np.sin(np.pi / 4) * np.sin(np.pi / 8),
    np.cos(np.pi / 8)
], dtype=float)

# Compute the L2-norm of the vector
vector_l2_norm = l2_norm(vector)

# Display the result
print(f"L2-norm of the given vector: {vector_l2_norm}")


L2-norm of the given vector: 1.0707224707676244
